env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - json
rules:
  indent:
    - error
    - tab
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-mixed-spaces-and-tabs:
    - 2
    - 'smart-tabs'
globals:
  __IP__: true

